trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPackage
  jobs:
  - job: Build
    steps:
    - checkout: self
    
    - task: Docker@2
      inputs:
        containerRegistry: 'dgcx_dev_appreg_serviceconnection_docker_registry'
        repository: 'withHaibunAZ'

        tags: withHaibunAZPOC
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      displayName: 'Build and push image'
    