trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: InstallNodeModules
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseNode@1
      inputs:
        version: '18.x'
    - script: |
        npm i azure-functions-core-tools@4 --unsafe-perm true

      displayName: 'Install Node modules'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'dgcx_dev_appreg_serviceconnection_collab-resources'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          func azure functionapp publish haibunpoc3 -b remote
      displayName: 'Deploy to Azure Function App'