trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPackage
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseNode@1

      inputs:
        version: '18.x'
    - script: |
        npm install
        npm run build
        npm run zip
      displayName: 'Build and Package'

- stage: Deploy

  jobs:

  - job: Deploy

    steps:  
    - checkout: none
    - task: Bash@3
      env:
        AZURE_SUBSCRIPTION: 'dgcx-gccollab'
        LOC: 'Canada Central'
        MY_STORAGE_ACCOUNT: 'devdatastorageacc'
        MY_RESOURCE_GROUP: 'rg-gctools-managedServices-dev'
        FUNCTION_APP_NAME: 'dev-haibun-gccollab' 
      inputs:
        script: |
          ls
          pwd
          az functionapp deployment source config-zip --resource-group $MY_RESOURCE_GROUP --name $FUNCTION_APP_NAME --src ./deploy.zip
      displayName: 'Deploy to Azure Function App'
